export enum TokensError {
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_MALFORMED = 'REFRESH_TOKEN_MALFORMED',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
}
